/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as CriarEventoRouteImport } from './routes/criar-evento'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProdutorRouteImport } from './routes/produtor'
import { Route as ProdutorPendenteRouteImport } from './routes/produtor-pendente'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ProdutorIndexRouteImport } from './routes/produtor/index'
import { Route as ProdutorNovoEventoRouteImport } from './routes/produtor/novo-evento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarEventoRoute = CriarEventoRouteImport.update({
  id: '/criar-evento',
  path: '/criar-evento',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorRoute = ProdutorRouteImport.update({
  id: '/produtor',
  path: '/produtor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorPendenteRoute = ProdutorPendenteRouteImport.update({
  id: '/produtor-pendente',
  path: '/produtor-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ProdutorIndexRoute = ProdutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorNovoEventoRoute = ProdutorNovoEventoRouteImport.update({
  id: '/novo-evento',
  path: '/novo-evento',
  getParentRoute: () => ProdutorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/criar-evento': typeof CriarEventoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/produtor': typeof ProdutorRouteWithChildren
  '/produtor-pendente': typeof ProdutorPendenteRoute
  '/produtor/novo-evento': typeof ProdutorNovoEventoRoute
  '/app/': typeof AppIndexRoute
  '/produtor/': typeof ProdutorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/criar-evento': typeof CriarEventoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/produtor-pendente': typeof ProdutorPendenteRoute
  '/produtor/novo-evento': typeof ProdutorNovoEventoRoute
  '/app': typeof AppIndexRoute
  '/produtor': typeof ProdutorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/criar-evento': typeof CriarEventoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/produtor': typeof ProdutorRouteWithChildren
  '/produtor-pendente': typeof ProdutorPendenteRoute
  '/produtor/novo-evento': typeof ProdutorNovoEventoRoute
  '/app/': typeof AppIndexRoute
  '/produtor/': typeof ProdutorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/checkin'
    | '/criar-evento'
    | '/eventos'
    | '/login'
    | '/produtor'
    | '/produtor-pendente'
    | '/produtor/novo-evento'
    | '/app/'
    | '/produtor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/checkin'
    | '/criar-evento'
    | '/eventos'
    | '/login'
    | '/produtor-pendente'
    | '/produtor/novo-evento'
    | '/app'
    | '/produtor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/checkin'
    | '/criar-evento'
    | '/eventos'
    | '/login'
    | '/produtor'
    | '/produtor-pendente'
    | '/produtor/novo-evento'
    | '/app/'
    | '/produtor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CheckinRoute: typeof CheckinRoute
  CriarEventoRoute: typeof CriarEventoRoute
  EventosRoute: typeof EventosRoute
  LoginRoute: typeof LoginRoute
  ProdutorRoute: typeof ProdutorRouteWithChildren
  ProdutorPendenteRoute: typeof ProdutorPendenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-evento': {
      id: '/criar-evento'
      path: '/criar-evento'
      fullPath: '/criar-evento'
      preLoaderRoute: typeof CriarEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor': {
      id: '/produtor'
      path: '/produtor'
      fullPath: '/produtor'
      preLoaderRoute: typeof ProdutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor-pendente': {
      id: '/produtor-pendente'
      path: '/produtor-pendente'
      fullPath: '/produtor-pendente'
      preLoaderRoute: typeof ProdutorPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/produtor/': {
      id: '/produtor/'
      path: '/'
      fullPath: '/produtor/'
      preLoaderRoute: typeof ProdutorIndexRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/novo-evento': {
      id: '/produtor/novo-evento'
      path: '/novo-evento'
      fullPath: '/produtor/novo-evento'
      preLoaderRoute: typeof ProdutorNovoEventoRouteImport
      parentRoute: typeof ProdutorRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProdutorRouteChildren {
  ProdutorNovoEventoRoute: typeof ProdutorNovoEventoRoute
  ProdutorIndexRoute: typeof ProdutorIndexRoute
}

const ProdutorRouteChildren: ProdutorRouteChildren = {
  ProdutorNovoEventoRoute: ProdutorNovoEventoRoute,
  ProdutorIndexRoute: ProdutorIndexRoute,
}

const ProdutorRouteWithChildren = ProdutorRoute._addFileChildren(
  ProdutorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CheckinRoute: CheckinRoute,
  CriarEventoRoute: CriarEventoRoute,
  EventosRoute: EventosRoute,
  LoginRoute: LoginRoute,
  ProdutorRoute: ProdutorRouteWithChildren,
  ProdutorPendenteRoute: ProdutorPendenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
