/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as CriarEventoRouteImport } from './routes/criar-evento'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProdutorRouteImport } from './routes/produtor'
import { Route as ProdutorPendenteRouteImport } from './routes/produtor-pendente'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminAprovacoesRouteImport } from './routes/admin/aprovacoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminCheckinMonitorRouteImport } from './routes/admin/checkin-monitor'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminEmailsRouteImport } from './routes/admin/emails'
import { Route as AdminPaisesMoedasRouteImport } from './routes/admin/paises-moedas'
import { Route as AdminPlanosRouteImport } from './routes/admin/planos'
import { Route as AdminProdutoresRouteImport } from './routes/admin/produtores'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppHistoricoRouteImport } from './routes/app/historico'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProdutorIndexRouteImport } from './routes/produtor/index'
import { Route as ProdutorConfiguracoesRouteImport } from './routes/produtor/configuracoes'
import { Route as ProdutorEquipeRouteImport } from './routes/produtor/equipe'
import { Route as ProdutorMarketingRouteImport } from './routes/produtor/marketing'
import { Route as ProdutorNovoEventoRouteImport } from './routes/produtor/novo-evento'
import { Route as ProdutorSuporteRouteImport } from './routes/produtor/suporte'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AdminMarketingIndexRouteImport } from './routes/admin/marketing/index'
import { Route as AdminMarketingAnunciosRouteImport } from './routes/admin/marketing/anuncios'
import { Route as AdminMarketingPublicidadeRouteImport } from './routes/admin/marketing/publicidade'
import { Route as ApiPublicEmailOauthCallbackRouteImport } from './routes/api/public/email-oauth-callback'
import { Route as ApiPublicUazapiWebhookRouteImport } from './routes/api/public/uazapi-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarEventoRoute = CriarEventoRouteImport.update({
  id: '/criar-evento',
  path: '/criar-evento',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorRoute = ProdutorRouteImport.update({
  id: '/produtor',
  path: '/produtor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorPendenteRoute = ProdutorPendenteRouteImport.update({
  id: '/produtor-pendente',
  path: '/produtor-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAprovacoesRoute = AdminAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinMonitorRoute = AdminCheckinMonitorRouteImport.update({
  id: '/checkin-monitor',
  path: '/checkin-monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaisesMoedasRoute = AdminPaisesMoedasRouteImport.update({
  id: '/paises-moedas',
  path: '/paises-moedas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutoresRoute = AdminProdutoresRouteImport.update({
  id: '/produtores',
  path: '/produtores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorIndexRoute = ProdutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorConfiguracoesRoute = ProdutorConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorEquipeRoute = ProdutorEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorMarketingRoute = ProdutorMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorNovoEventoRoute = ProdutorNovoEventoRouteImport.update({
  id: '/novo-evento',
  path: '/novo-evento',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorSuporteRoute = ProdutorSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => ProdutorRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMarketingIndexRoute = AdminMarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingAnunciosRoute = AdminMarketingAnunciosRouteImport.update({
  id: '/marketing/anuncios',
  path: '/marketing/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingPublicidadeRoute =
  AdminMarketingPublicidadeRouteImport.update({
    id: '/marketing/publicidade',
    path: '/marketing/publicidade',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiPublicEmailOauthCallbackRoute =
  ApiPublicEmailOauthCallbackRouteImport.update({
    id: '/api/public/email-oauth-callback',
    path: '/api/public/email-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUazapiWebhookRoute = ApiPublicUazapiWebhookRouteImport.update({
  id: '/api/public/uazapi-webhook',
  path: '/api/public/uazapi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/criar-evento': typeof CriarEventoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/produtor': typeof ProdutorRouteWithChildren
  '/produtor-pendente': typeof ProdutorPendenteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/checkin-monitor': typeof AdminCheckinMonitorRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/paises-moedas': typeof AdminPaisesMoedasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/produtores': typeof AdminProdutoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/produtor/configuracoes': typeof ProdutorConfiguracoesRoute
  '/produtor/equipe': typeof ProdutorEquipeRoute
  '/produtor/marketing': typeof ProdutorMarketingRoute
  '/produtor/novo-evento': typeof ProdutorNovoEventoRoute
  '/produtor/suporte': typeof ProdutorSuporteRoute
  '/app/': typeof AppIndexRoute
  '/produtor/': typeof ProdutorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/marketing/anuncios': typeof AdminMarketingAnunciosRoute
  '/admin/marketing/publicidade': typeof AdminMarketingPublicidadeRoute
  '/api/public/email-oauth-callback': typeof ApiPublicEmailOauthCallbackRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/criar-evento': typeof CriarEventoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/produtor-pendente': typeof ProdutorPendenteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/checkin-monitor': typeof AdminCheckinMonitorRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/paises-moedas': typeof AdminPaisesMoedasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/produtores': typeof AdminProdutoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/produtor/configuracoes': typeof ProdutorConfiguracoesRoute
  '/produtor/equipe': typeof ProdutorEquipeRoute
  '/produtor/marketing': typeof ProdutorMarketingRoute
  '/produtor/novo-evento': typeof ProdutorNovoEventoRoute
  '/produtor/suporte': typeof ProdutorSuporteRoute
  '/app': typeof AppIndexRoute
  '/produtor': typeof ProdutorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/marketing/anuncios': typeof AdminMarketingAnunciosRoute
  '/admin/marketing/publicidade': typeof AdminMarketingPublicidadeRoute
  '/api/public/email-oauth-callback': typeof ApiPublicEmailOauthCallbackRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/admin/marketing': typeof AdminMarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/criar-evento': typeof CriarEventoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/produtor': typeof ProdutorRouteWithChildren
  '/produtor-pendente': typeof ProdutorPendenteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/checkin-monitor': typeof AdminCheckinMonitorRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/paises-moedas': typeof AdminPaisesMoedasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/produtores': typeof AdminProdutoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/produtor/configuracoes': typeof ProdutorConfiguracoesRoute
  '/produtor/equipe': typeof ProdutorEquipeRoute
  '/produtor/marketing': typeof ProdutorMarketingRoute
  '/produtor/novo-evento': typeof ProdutorNovoEventoRoute
  '/produtor/suporte': typeof ProdutorSuporteRoute
  '/app/': typeof AppIndexRoute
  '/produtor/': typeof ProdutorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/marketing/anuncios': typeof AdminMarketingAnunciosRoute
  '/admin/marketing/publicidade': typeof AdminMarketingPublicidadeRoute
  '/api/public/email-oauth-callback': typeof ApiPublicEmailOauthCallbackRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/checkin'
    | '/criar-evento'
    | '/eventos'
    | '/login'
    | '/mcp'
    | '/produtor'
    | '/produtor-pendente'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/aprovacoes'
    | '/admin/auditoria'
    | '/admin/chat'
    | '/admin/checkin-monitor'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/paises-moedas'
    | '/admin/planos'
    | '/admin/produtores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/auth/callback'
    | '/produtor/configuracoes'
    | '/produtor/equipe'
    | '/produtor/marketing'
    | '/produtor/novo-evento'
    | '/produtor/suporte'
    | '/app/'
    | '/produtor/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/marketing/anuncios'
    | '/admin/marketing/publicidade'
    | '/api/public/email-oauth-callback'
    | '/api/public/uazapi-webhook'
    | '/admin/marketing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/checkin'
    | '/criar-evento'
    | '/eventos'
    | '/login'
    | '/mcp'
    | '/produtor-pendente'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/aprovacoes'
    | '/admin/auditoria'
    | '/admin/chat'
    | '/admin/checkin-monitor'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/paises-moedas'
    | '/admin/planos'
    | '/admin/produtores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/auth/callback'
    | '/produtor/configuracoes'
    | '/produtor/equipe'
    | '/produtor/marketing'
    | '/produtor/novo-evento'
    | '/produtor/suporte'
    | '/app'
    | '/produtor'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/marketing/anuncios'
    | '/admin/marketing/publicidade'
    | '/api/public/email-oauth-callback'
    | '/api/public/uazapi-webhook'
    | '/admin/marketing'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/checkin'
    | '/criar-evento'
    | '/eventos'
    | '/login'
    | '/mcp'
    | '/produtor'
    | '/produtor-pendente'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/aprovacoes'
    | '/admin/auditoria'
    | '/admin/chat'
    | '/admin/checkin-monitor'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/paises-moedas'
    | '/admin/planos'
    | '/admin/produtores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/auth/callback'
    | '/produtor/configuracoes'
    | '/produtor/equipe'
    | '/produtor/marketing'
    | '/produtor/novo-evento'
    | '/produtor/suporte'
    | '/app/'
    | '/produtor/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/marketing/anuncios'
    | '/admin/marketing/publicidade'
    | '/api/public/email-oauth-callback'
    | '/api/public/uazapi-webhook'
    | '/admin/marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CheckinRoute: typeof CheckinRoute
  CriarEventoRoute: typeof CriarEventoRoute
  EventosRoute: typeof EventosRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ProdutorRoute: typeof ProdutorRouteWithChildren
  ProdutorPendenteRoute: typeof ProdutorPendenteRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicEmailOauthCallbackRoute: typeof ApiPublicEmailOauthCallbackRoute
  ApiPublicUazapiWebhookRoute: typeof ApiPublicUazapiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-evento': {
      id: '/criar-evento'
      path: '/criar-evento'
      fullPath: '/criar-evento'
      preLoaderRoute: typeof CriarEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor': {
      id: '/produtor'
      path: '/produtor'
      fullPath: '/produtor'
      preLoaderRoute: typeof ProdutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor-pendente': {
      id: '/produtor-pendente'
      path: '/produtor-pendente'
      fullPath: '/produtor-pendente'
      preLoaderRoute: typeof ProdutorPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aprovacoes': {
      id: '/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AdminAprovacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkin-monitor': {
      id: '/admin/checkin-monitor'
      path: '/checkin-monitor'
      fullPath: '/admin/checkin-monitor'
      preLoaderRoute: typeof AdminCheckinMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paises-moedas': {
      id: '/admin/paises-moedas'
      path: '/paises-moedas'
      fullPath: '/admin/paises-moedas'
      preLoaderRoute: typeof AdminPaisesMoedasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtores': {
      id: '/admin/produtores'
      path: '/produtores'
      fullPath: '/admin/produtores'
      preLoaderRoute: typeof AdminProdutoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor/': {
      id: '/produtor/'
      path: '/'
      fullPath: '/produtor/'
      preLoaderRoute: typeof ProdutorIndexRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/configuracoes': {
      id: '/produtor/configuracoes'
      path: '/configuracoes'
      fullPath: '/produtor/configuracoes'
      preLoaderRoute: typeof ProdutorConfiguracoesRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/equipe': {
      id: '/produtor/equipe'
      path: '/equipe'
      fullPath: '/produtor/equipe'
      preLoaderRoute: typeof ProdutorEquipeRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/marketing': {
      id: '/produtor/marketing'
      path: '/marketing'
      fullPath: '/produtor/marketing'
      preLoaderRoute: typeof ProdutorMarketingRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/novo-evento': {
      id: '/produtor/novo-evento'
      path: '/novo-evento'
      fullPath: '/produtor/novo-evento'
      preLoaderRoute: typeof ProdutorNovoEventoRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/suporte': {
      id: '/produtor/suporte'
      path: '/suporte'
      fullPath: '/produtor/suporte'
      preLoaderRoute: typeof ProdutorSuporteRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing/': {
      id: '/admin/marketing/'
      path: '/marketing'
      fullPath: '/admin/marketing/'
      preLoaderRoute: typeof AdminMarketingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/anuncios': {
      id: '/admin/marketing/anuncios'
      path: '/marketing/anuncios'
      fullPath: '/admin/marketing/anuncios'
      preLoaderRoute: typeof AdminMarketingAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/publicidade': {
      id: '/admin/marketing/publicidade'
      path: '/marketing/publicidade'
      fullPath: '/admin/marketing/publicidade'
      preLoaderRoute: typeof AdminMarketingPublicidadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/email-oauth-callback': {
      id: '/api/public/email-oauth-callback'
      path: '/api/public/email-oauth-callback'
      fullPath: '/api/public/email-oauth-callback'
      preLoaderRoute: typeof ApiPublicEmailOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uazapi-webhook': {
      id: '/api/public/uazapi-webhook'
      path: '/api/public/uazapi-webhook'
      fullPath: '/api/public/uazapi-webhook'
      preLoaderRoute: typeof ApiPublicUazapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAprovacoesRoute: typeof AdminAprovacoesRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCheckinMonitorRoute: typeof AdminCheckinMonitorRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminPaisesMoedasRoute: typeof AdminPaisesMoedasRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminProdutoresRoute: typeof AdminProdutoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminMarketingAnunciosRoute: typeof AdminMarketingAnunciosRoute
  AdminMarketingPublicidadeRoute: typeof AdminMarketingPublicidadeRoute
  AdminMarketingIndexRoute: typeof AdminMarketingIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAprovacoesRoute: AdminAprovacoesRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCheckinMonitorRoute: AdminCheckinMonitorRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminPaisesMoedasRoute: AdminPaisesMoedasRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminProdutoresRoute: AdminProdutoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminMarketingAnunciosRoute: AdminMarketingAnunciosRoute,
  AdminMarketingPublicidadeRoute: AdminMarketingPublicidadeRoute,
  AdminMarketingIndexRoute: AdminMarketingIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoricoRoute: AppHistoricoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProdutorRouteChildren {
  ProdutorConfiguracoesRoute: typeof ProdutorConfiguracoesRoute
  ProdutorEquipeRoute: typeof ProdutorEquipeRoute
  ProdutorMarketingRoute: typeof ProdutorMarketingRoute
  ProdutorNovoEventoRoute: typeof ProdutorNovoEventoRoute
  ProdutorSuporteRoute: typeof ProdutorSuporteRoute
  ProdutorIndexRoute: typeof ProdutorIndexRoute
}

const ProdutorRouteChildren: ProdutorRouteChildren = {
  ProdutorConfiguracoesRoute: ProdutorConfiguracoesRoute,
  ProdutorEquipeRoute: ProdutorEquipeRoute,
  ProdutorMarketingRoute: ProdutorMarketingRoute,
  ProdutorNovoEventoRoute: ProdutorNovoEventoRoute,
  ProdutorSuporteRoute: ProdutorSuporteRoute,
  ProdutorIndexRoute: ProdutorIndexRoute,
}

const ProdutorRouteWithChildren = ProdutorRoute._addFileChildren(
  ProdutorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CheckinRoute: CheckinRoute,
  CriarEventoRoute: CriarEventoRoute,
  EventosRoute: EventosRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ProdutorRoute: ProdutorRouteWithChildren,
  ProdutorPendenteRoute: ProdutorPendenteRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicEmailOauthCallbackRoute: ApiPublicEmailOauthCallbackRoute,
  ApiPublicUazapiWebhookRoute: ApiPublicUazapiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
